# Generated by Django 4.2.1 on 2023-06-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='courier_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
